### ISSUE TITLE
SHA mismatch on the cask update to v4.0.0-M2 

### ISSUE THREAD

**Issue by sambao21** [micronaut-projects/homebrew-tap#2]
Trying to install micronaut from brew today and got the following SHA256 mismatch error.  Is anyone else seeing this and can confirm the mismatch from the [last commit](https://github.com/micronaut-projects/homebrew-tap/commit/a077cb5f81204b282169357c86bf26d649741180)?

```
> brew install micronaut-projects/tap/micronaut --cask
==> Downloading https://github.com/micronaut-projects/micronaut-starter/releases/download/
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset
################################################################################### 100.0%
Error: SHA256 mismatch
Expected: edd245a15e4b253967c6ba1db1e13a6ff9e0af689a0a3392f3210e3f70af8c9b
  Actual: 15378d06056f1a5e8678c23ddfb24b2a7705cfc4a9a2e6b9580ef81297994506
    File: ~/Library/Caches/Homebrew/downloads/2503e9316b267e23f512d0c2d15d89259c7e402e99e85ad7c179b7a611d15bb3--mn-darwin-amd64-v4.0.0-M2.zip
To retry an incomplete download, remove the file above.
```

**Comment by alvarosanchez** [comment]
4.0.0-M2 was the first 4.0.x release and had some road bumps that @sdelamo had to fix along the way. Let's hope the next attempt works better.

Meanwhile, I have manually fixed the SHA

**Comment by sambao21** [comment]
Thank you for the quick turn around

**Comment by sdelamo** [comment]
thanks @alvarosanchez . Yes, in theory 🤞🏻the next milestone should be fine.
